name: Deploy to GitHub pages
on:
  push:
    # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate static vuepress files
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd build
          cp index.html 404.html
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m ':wrench: deploy'
        env:
          VUE_APP_GHOST_CONTENT_API_KEY: ${{ secrets.VUE_APP_GHOST_CONTENT_API_KEY }}
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
          branch: gh-pages
          force: true
          directory: ./build
